#!/bin/bash

USER=${1:-drupal}
#mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
mysql -u root -e "CREATE USER IF NOT EXISTS '$USER'@'%';"
mysql -u root -e "CREATE DATABASE IF NOT EXISTS test001;"
mysql -u root -e "CREATE DATABASE IF NOT EXISTS test002;"
mysql -u root -e "CREATE DATABASE IF NOT EXISTS test005;"
mysql -u root -e "CREATE DATABASE IF NOT EXISTS test006a;"
mysql -u root -e "CREATE DATABASE IF NOT EXISTS test006b;"
mysql -u root -e "CREATE DATABASE IF NOT EXISTS test008;"
mysql -u root -e "CREATE DATABASE IF NOT EXISTS test009;"
mysql -u root -e "CREATE DATABASE IF NOT EXISTS test010;"
mysql -u root -e "CREATE DATABASE IF NOT EXISTS test011;"
mysql -u root -e "CREATE DATABASE IF NOT EXISTS test012;"
mysql -u root -e "GRANT ALL PRIVILEGES ON test001.* TO '$USER'@'%' WITH GRANT OPTION;"
mysql -u root -e "GRANT ALL PRIVILEGES ON test002.* TO '$USER'@'%' WITH GRANT OPTION;"
mysql -u root -e "GRANT ALL PRIVILEGES ON test005.* TO '$USER'@'%' WITH GRANT OPTION;"
mysql -u root -e "GRANT ALL PRIVILEGES ON test006a.* TO '$USER'@'%' WITH GRANT OPTION;"
mysql -u root -e "GRANT ALL PRIVILEGES ON test006b.* TO '$USER'@'%' WITH GRANT OPTION;"
mysql -u root -e "GRANT ALL PRIVILEGES ON test008.* TO '$USER'@'%' WITH GRANT OPTION;"
mysql -u root -e "GRANT ALL PRIVILEGES ON test009.* TO '$USER'@'%' WITH GRANT OPTION;"
mysql -u root -e "GRANT ALL PRIVILEGES ON test010.* TO '$USER'@'%' WITH GRANT OPTION;"
mysql -u root -e "GRANT ALL PRIVILEGES ON test011.* TO '$USER'@'%' WITH GRANT OPTION;"
mysql -u root -e "GRANT ALL PRIVILEGES ON test012.* TO '$USER'@'%' WITH GRANT OPTION;"
mysql -u root -e "GRANT SUPER,LOCK TABLES ON *.* TO '$USER'@'%';"
mysql -u root -e "GRANT SELECT ON mysql.proc to '$USER'@'%';"
mysql -u root -e "FLUSH PRIVILEGES;"

echo "Done"
